# Generated by Django 4.0.6 on 2022-08-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_suit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='suit_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='suit_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='suit_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='suit_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='suit_price',
            new_name='price',
        ),
    ]
