# Generated by Django 4.0.6 on 2022-08-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_suit_brand_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
    ]
